### ISSUE TITLE
Using em instead rem

### ISSUE THREAD

**Issue by alekspetrov** [hiulit/Sassy-Gridlover#1]
First of all thx for your work it's very usefull.
How about em? Can I re-config Gridlover to use em instead rem?

**Comment by hiulit** [comment]
There's a branch for this issue https://github.com/hiulit/Sassy-Gridlover/tree/em-support

**Comment by hiulit** [comment]
Good news everyone!

@walmokrani help a lot with this issue https://github.com/hiulit/Sassy-Gridlover/pull/7. I have to take a look at it so I can merge it. But it's looking good :D

**Comment by hiulit** [comment]
Hey guys @alekspetrov @cibulka !
I've just released [v2.0.0](https://github.com/hiulit/Sassy-Gridlover/releases) with **em support**! Check it out and tell me what you think or if it works for you! ;)

Thanks again to @walmokrani !
