### ISSUE TITLE
something is odd here

### ISSUE THREAD

**Issue by designermonkey** [hiulit/Sassy-Gridlover#11]
https://github.com/hiulit/Sassy-Gridlover/blob/master/sassy-gridlover/_functions.scss#L5

that function will never get past the first if statement.

**Comment by hiulit** [comment]
Hi @designermonkey ,
You are right. I've just updated the `exponent` and `pow` functions from https://github.com/at-import/Sassy-math/blob/master/sass/math.scss

See: https://github.com/hiulit/Sassy-Gridlover/commit/26d26b2d9a3457a21c03b845b69e9e5eefff010e

**Comment by designermonkey** [comment]
:)

I didn't know if it were a catch for if `pow` hadn't been defined, but my sass compiler errors on it anyway.

**Comment by hiulit** [comment]
Glad it's working! :)

Just a heads up. I'll be releasing a new version with breaking changes later today, related to [this issue](https://github.com/hiulit/Sassy-Gridlover/issues/9). Basically I've added a `sgl-` prefix to all the functions and I've seized the opportunity to shrunk the mixins'  `sassy-gridlover-` prefix to `sgl-` as well. ;)

**Comment by hiulit** [comment]
New release https://github.com/hiulit/Sassy-Gridlover/releases/tag/v3.0.0
