### ISSUE TITLE
Rewrite $step3 on sgl-heading mixins ?

### ISSUE THREAD

**Issue by rizqinizamil** [hiulit/Sassy-Gridlover#19]
When I use steps more than 3, let say 5 to 0, I need to re-adjust sgl-heading mixins. Change margin-bottom to 0.
Because when I use step 3 for H3 it will be make more margin bottom.
What do you think?

**Comment by hiulit** [comment]
I'm sorry, I don't quite understand what you mean when you say:
> When I use steps more than 3, let say 5 to 0

You can take a look at the documentation to see [how to use sgl-heading](https://github.com/hiulit/Sassy-Gridlover#sgl-heading).

Take into account that **Sassy-Gridlover** is a port of [Gridlover](https://www.gridlover.net/try), so, in principle, **Sassy-Gridlover** does (or does not) what **Gridlover** does.

**Comment by rizqinizamil** [comment]
Hi, thank you for your reply. I'm sorry took so long to reply back.
Actually I don't use default setting from Gridlover, but Gridlover also let user to change the setting. For example I use step 5 (instead of step 3) for H1
![Image of H1](https://cldup.com/99nv2EC2UR.png)

I hope you understand what I mean 😄

**Comment by hiulit** [comment]
Ok, I see it now, Yes, you are right! I don't have much time right now, but I'll take a look at it whenever I can.
Also, you could send me a Pull Request if you want. :D

**Comment by hiulit** [comment]
Just a heads up, I'm working on it. I'll keep you updated ;)

**Comment by hiulit** [comment]
@rizqinizamil I just published [v6.0.0](https://github.com/hiulit/Sassy-Gridlover/releases/tag/v6.0.0) with the changes ;)

**Comment by rizqinizamil** [comment]
Wow! This is another christmas gift 😄 
I'll give it a try! Thank you!

**Comment by hiulit** [comment]
Yes, please, try it and let me know if it works. In principle, it mimics the same behaviour as Gridlover.
