### ISSUE TITLE
dart-sass: deprecation warning: !global assignments won't be able to declare new variables

### ISSUE THREAD

**Issue by wujekbogdan** [hiulit/Sassy-Gridlover#20]
### Expected behavior

No deprecation warnings in the console.

### Actual behavior

dart-sass (`v 1.17.2`) is reporting deprecation warnings.

```
DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
declare new variables. Consider adding `$sgl-root-font-size: null` at the top level.
```

### Steps to reproduce the behaviour

Use the official [`sass`](https://github.com/sass/dart-sass) module instead of an unofficial `node-sass` module to compile the code.

**Comment by hiulit** [comment]
I've added `$sgl-root-font-size: null`.
Could you please try the `develop` branch and see if everything works fine?

**Comment by wujekbogdan** [comment]
@hiulit 
It's fine in the `develop` branch. Thanks!

**Comment by hiulit** [comment]
Ok! I'll merge it into the `master` branch and I'll release a new version.

Thanks!
