### ISSUE TITLE
Default export

### ISSUE THREAD

**Issue by mod3x** [hiulit/Sassy-Gridlover#21]
It would be cool to add path to main file in package.json, so importing with bundlers won't be so painful like this:
`@import '~sassy-gridlover/sassy-gridlover/sassy-gridlover';`

for example, [how it implements](https://github.com/necolas/normalize.css/blob/fc091cce1534909334c1911709a39c22d406977b/package.json#L5) in normalize.css

**Comment by hiulit** [comment]
Something like this would work? `"main": "sassy-gridlover/sassy-gridlover/_sassy-gridlover.scss",`

**Comment by mod3x** [comment]
second option :ok_hand:

**Comment by hiulit** [comment]
So the second path is the correct one?

This one? `"main": "sassy-gridlover/_sassy-gridlover.scss"`

**Comment by mod3x** [comment]
yep

**Comment by hiulit** [comment]
Got it! I'll will add it asap! 👍

**Comment by mod3x** [comment]
thanks :+1:

**Comment by hiulit** [comment]
Done! [v6.0.4](https://github.com/hiulit/Sassy-Gridlover/releases/tag/v6.0.4) has been released :)
