### ISSUE TITLE
Error: Invalid null operation: "null times 2.36859"

### ISSUE THREAD

**Issue by josueq** [hiulit/Sassy-Gridlover#22]
Hello there, first of all, thank u so much for this awesome tool. I've used old version but now I've some troubles at compile. The error shows:
Error: Invalid null operation: "null times 2.36859".
        on line 192 of ../scss/vendors/sassy-gridlover/_sassy-gridlover.scss, in mixin `sgl-heading`
        from line 29 of ../scss/pages/_single.scss
        from line 41 of ../scss/main.scss
>>     $computed-font-size: round($font-size * sgl-exponent($scale, $font-size-
   -------------------------------^

I'm using npm 5.5.1
node v9.3.0
gulp 3.9.1

**Comment by hiulit** [comment]
First of all, are you using Sass Dart? Because old Ruby Sass is now deprecated.

A part from that, I need more information. Could you paste your `sgl-heading` mixin?
For example:
```
h1 {
    @include sgl-heading(3, 0, 1, 2);
}
```

Also, if you are updating from an older version, check out the new [documentation](https://github.com/hiulit/Sassy-Gridlover/blob/master/README.md) and the [CHANGELOG](https://github.com/hiulit/Sassy-Gridlover/blob/master/CHANGELOG.md) because there have been many changes, some of them breaking old stuff.
**Sassy-Gridlover** is now at **v6.0.4**.

**Comment by josueq** [comment]
thanks for your answer.

I'm not using Sass Dart.

Here is the code when 

```
@import 'vendors/sassy-gridlover/sassy-gridlover';
.
.
.

.articleTitle{
               @include sgl-heading(3, 0, 1, 2);
                text-decoration: none;
		font-weight: bold;
		display: inline-block;
}
```

I made the changes according to the indications that are in the new version guide.

**Comment by hiulit** [comment]
My first suggestion would be to update to Sass Dart, because that's the official Sass now. Ruby Sass is deprecated and Sassy-Gridlover is up to date to use Sass Dart.

Now, your code looks fine.
Are you using any other Sassy-Gridlover mixins? Apart from the one in the code above. Is this the only mixin that breaks?

**Comment by josueq** [comment]
I just updated to Sass Dart. Now it's written that sgl-heading need only 3 arguments.

I changed the reference in the gulpfile as well.
<img width="498" alt="Screenshot 2019-03-29 at 14 55 40" src="https://user-images.githubusercontent.com/5794108/55237567-bfba2280-5232-11e9-9fad-5153c84dc088.png">

**Comment by hiulit** [comment]
I don't know why but it seems that you are lacking the `$font-size` variable, that's why it returns `null`

**Comment by hiulit** [comment]
Oh, are you using `sgl-html()`? Because you should.

Add this:

```
html {
    @include sgl-html;
}
```

At the top of you code, line in the example https://github.com/hiulit/Sassy-Gridlover#example-usage

**Comment by josueq** [comment]
thank u again for your instruction. I do not have this problem anymore. I had to add this line
`@include sgl-html;`
to the class where I use:
`@include sgl-heading(3, 0, 1, 2);`
and it works. 
Duplicate code is generated, but at least, works. I didn't have that problem with the previous version. With this version, it is not possible to use the mixin from different separate files?

I 'm using the 7-1 pattern ([https://github.com/HugoGiraudel/sass-boilerplate](url) and I defined:
`@include sgl-html;`
in the base file, the variables in variables file and another calls to sgl-heading from components, layouts or pages files.

**Comment by hiulit** [comment]
I'm glad is working! :)

You should add `@include sgl-html;` ONLY in `html {}`, for example in your `reset.scss` or the like.

Like this:
```
html {
    @include sgl-html;
}
```

Only use it one time. It sets the base font size for the project.

**Comment by hiulit** [comment]
Maybe it should be stated clearly that

```
html {
    @include sgl-html;
}
```

is mandatory.

**Comment by josueq** [comment]
unfortunately, when I remove it, doesn't work :(
<img width="656" alt="Screenshot 2019-04-01 at 13 15 44" src="https://user-images.githubusercontent.com/5794108/55323964-f38a8780-5480-11e9-8012-c144c554a79f.png">

**Comment by hiulit** [comment]
No, of course! You should not remove it! But you should only add it once:

```
html {
    @include sgl-html;
}
```

Wherever you have you reset styles or something similar, try to add it there.
