### ISSUE TITLE
use less generic functions names

### ISSUE THREAD

**Issue by wujekbogdan** [hiulit/Sassy-Gridlover#9]
IMO functions should be prefixed, because names are too generic. It can cause conflicts. For example `rem-calc()` may cause conflict with foundation framework. I suggest to prefix all the functions with `$sgl-*`

**Comment by hiulit** [comment]
Hey! Thanks!
Maybe you are right. I'll take a look at it.

**Comment by hiulit** [comment]
This should do it, right @wujekbogdan ?  https://github.com/hiulit/Sassy-Gridlover/commit/1a091df7bdfb926838b4244479e31615b58b9683

**Comment by hiulit** [comment]
New release https://github.com/hiulit/Sassy-Gridlover/releases/tag/v3.0.0

**Comment by wujekbogdan** [comment]
Thanks. Perfect!
